### ISSUE TITLE
User-defined groups

### ISSUE THREAD

**Issue by perappu** [perappu/WhoSaidWhatNow#7]
I want to be able to organize tracked players in user-defined groups. Possibility of custom & automatic labels?

**Comment by erunseelie** [comment]
> a new approach for groups: just simple new "view" tabs that hold all players currently tracked, and you can select/deselect who you want to show there at any time

- avoids new Group object creation
- add a search/filter bar for Players at top of overall selection area?

**Comment by perappu** [comment]
Added to main branch in 01e31ea
